### ISSUE TITLE
Moving CV ontologies to another repo

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/mzML#1]
Hi all,

One thing I'd like to bring up as an idea:
since there is migratory adaption to be made by most CV consumers due to the GitHub move anyway,
might it not also be good to create an own repository for the CV?
-It is not only used in the mzML domain (predominantly though), so it is not the most intuitive place to look for it. 
1- We may have a readme.md for the repository or even a github page
2- And CV issues would not clog the mzML repository
3- It would make it way easier to propose changes (fork & branch + change -> pullrequest: github shows the diff nicely rendered on the pullrequest page, where additional comments and discussion can be made.)

furthermore, a small remark, if you want to use direct web file access via your programs
https://raw.githubusercontent.com/HUPO-PSI/mzML/master/cv/psi-ms.obo
might be the more robust choice. Or https://raw.githubusercontent.com/HUPO-PSI/ControlledVocabulary/master/... if we dare this additional step.

In any case, thanks for the work on the CV, Gerhard!

best,
@mwalzer

**Comment by edeutsch** [comment]
closing as largely obsolete
