### ISSUE TITLE
mzML validator

### ISSUE THREAD

**Issue by UKQIDA** [HUPO-PSI/mzML#3]
Hi,
I wonder where can I find the mzML validator now. 
Thanks
Da

**Comment by mwalzer** [comment]
Hi Da,
seems all sites where you could do online validation have shut down, at least to my knowledge. If you have singularity or docker on your system, you can use one of the OpenMS containers I built (`docker pull mwalzer/openms-batteries-included:V2.3.0`) and run the validator. 
```
XMLValidator -schema <Schema to validate against>  -in <Your mzML file> 
```
You can find the latest schema [here](https://github.com/HUPO-PSI/mzML/blob/master/schema/schema_1.1/mzML1.1.1_idx.xsd)
Idk about the jmzML validator, though.
HTH

**Comment by UKQIDA** [comment]
Hi Mathias,
Thanks. I'll give OpenMS a try and let you know if failed.
Da

**Comment by hechth** [comment]
I think you can basically use any xml validator tool, you just have to pass in the file and the XSD schema.

**Comment by edeutsch** [comment]
closing for now. Please reopen if this remains an issue.
