### ISSUE TITLE
`xs:ID` type of `id` attribute of `RunType` makes many mzml files starting with digits as file or sample name invalid.

### ISSUE THREAD

**Issue by hechth** [HUPO-PSI/mzML#8]
We're currently implementing a validator tool in Galaxy that simply takes an mzml file and uses the XSD schema to validate files using pyxml or xmllinter and we found that the `<run> ... </run>` field has an id attribute which has to be an `xs:ID` type, meaning it can't start with a number. But proteowizard seems to be filling this field with the sample name, which can contain a number at the start (and often does, like the position, order in the study, timestamp etc.), meaning that many mzml files which start with a number are technically invalid.

I personally don't see a reason why the `id` of the `RunType` can't be a `xs:string` - was there a specific reason for the decision?

I'd therefore like to propose to change the `id` attribute of the `RunType` from `xs:ID` to `xs:string`.

If you agree with the change I can open up a PR with the requested changes to the XSD file. Is there anything else that has to be adapted to make this change?

**Comment by edeutsch** [comment]
Closing since addressed in PR #9
